// src/pages/Signup.jsx
import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { useAuth } from "../context/AuthContext.jsx";
import { isValidationError } from "../utils/errors.js";

export default function Signup(){
  const navigate = useNavigate();
  const { signupUser } = useAuth();

  const { register, handleSubmit, formState:{errors:rhfErrors} } = useForm({
    defaultValues:{ email:"", password:"" }
  });

  const [serverError,setServerError] = useState(null);

  async function onSubmit(values){
    setServerError(null);
    const result = await signupUser({
      email: values.email.trim(),
      password: values.password,
    });

    if(!result.ok){
      setServerError(result.error);
      return;
    }
    navigate("/dashboard");
  }

  function fieldServerError(name){
    if(serverError?.details?.fields?.[name]){
      return serverError.details.fields[name];
    }
    return null;
  }

  const topLevelMessage =
    serverError && isValidationError(serverError)
      ? serverError.message
      : null;

  return (
    <main className="min-h-screen flex flex-col bg-surface-subtle"> 
      <div className="flex-1 flex items-center justify-center page-shell py-16">
        <div className="card w-full max-w-sm p-6 space-y-6">
          <div>
            <h1 className="text-display-md text-text font-semibold">Create account</h1>
            <p className="text-body-sm text-text-dim">
              We'll store your account in localStorage.
            </p>
          </div>

          {topLevelMessage ? (
            <div
              className="rounded-card border border-danger-border bg-danger-bg px-3 py-2 text-danger-text text-body-sm"
              role="alert"
              aria-live="assertive"
            >
              {topLevelMessage}
            </div>
          ):null}

          <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}>
            <div className="space-y-2">
              <label className="block text-body-sm font-medium text-text" htmlFor="email">
                Email
              </label>
              <input
                id="email"
                className="w-full rounded-card border border-surface-border bg-surface px-3 py-2 text-body-md text-text focus-visible:ring-brand-500"
                type="email"
                placeholder="you@example.com"
                {...register("email",{
                  required:"Email is required.",
                  validate:(val)=>{
                    if(!val.includes("@")) return "Enter a valid email.";
                    return true;
                  }
                })}
              />
              <p className="text-body-sm text-danger-text" role="alert">
                {rhfErrors.email?.message || fieldServerError("email")}
              </p>
            </div>

            <div className="space-y-2">
              <label className="block text-body-sm font-medium text-text" htmlFor="password">
                Password
              </label>
              <input
                id="password"
                className="w-full rounded-card border border-surface-border bg-surface px-3 py-2 text-body-md text-text focus-visible:ring-brand-500"
                type="password"
                placeholder="Create a password"
                {...register("password",{
                  required:"Password is required.",
                  minLength:{value:6,message:"Minimum 6 characters."}
                })}
              />
              <p className="text-body-sm text-danger-text" role="alert">
                {rhfErrors.password?.message || fieldServerError("password")}
              </p>
            </div>

            <button
              type="submit"
              className="w-full rounded-pill bg-brand-600 px-4 py-2 text-white text-sm font-medium hover:bg-brand-700 focus-visible:ring-2 focus-visible:ring-brand-500"
            >
              Sign up
            </button>
          </form>

          <div className="text-center text-body-sm text-text-dim">
            Already have an account?{" "}
            <Link
              className="text-brand-600 hover:text-brand-700 font-medium focus-visible:ring-2 focus-visible:ring-brand-500 rounded-sm"
              to="/auth/login"
            >
              Log in
            </Link>
          </div>

          <div className="text-center text-body-xs text-text-dim text-[12px] leading-[16px]">
            Test login after signup: test@ticketapp.test / password123
          </div>
        </div>
      </div>

      <footer className="border-t border-surface-border bg-surface py-4 text-center text-body-xs text-text-dim">
        <div className="page-shell">
          © 2025 TicketApp — All rights reserved.
        </div>
      </footer>
    </main>
  );
}

// src/pages/Signup.vue
<template>
  <main class="min-h-screen flex flex-col bg-surface-subtle text-text">
    <Navbar />

    <div class="flex-1 flex items-center justify-center page-shell py-16">
      <div class="card w-full max-w-sm p-6 space-y-6">
        <div>
          <h1 class="text-display-md text-text font-semibold">Create account</h1>
          <p class="text-body-sm text-text-dim">We'll store your account in localStorage.</p>
        </div>

        <div v-if="topLevelMessage" class="rounded-card border border-danger-border bg-danger-bg px-3 py-2 text-danger-text text-body-sm" role="alert" aria-live="assertive">
          {{ topLevelMessage }}
        </div>

        <form class="space-y-4" @submit.prevent="handleSubmit">
          <div class="space-y-2">
            <label class="block text-body-sm font-medium text-text" for="email">Email</label>
            <input id="email" v-model="email" class="w-full rounded-card border border-surface-border bg-surface px-3 py-2 text-body-md text-text focus-visible:ring-brand-500" type="email" placeholder="you@example.com" />
            <p class="text-body-sm text-danger-text" role="alert">{{ errors.email || fieldServerError('email') }}</p>
          </div>

          <div class="space-y-2">
            <label class="block text-body-sm font-medium text-text" for="password">Password</label>
            <input id="password" v-model="password" class="w-full rounded-card border border-surface-border bg-surface px-3 py-2 text-body-md text-text focus-visible:ring-brand-500" type="password" placeholder="Create a password" />
            <p class="text-body-sm text-danger-text" role="alert">{{ errors.password || fieldServerError('password') }}</p>
          </div>

          <button type="submit" class="w-full rounded-pill bg-brand-600 px-4 py-2 text-white text-sm font-medium hover:bg-brand-700 focus-visible:ring-2 focus-visible:ring-brand-500">
            Sign up
          </button>
        </form>

        <div class="text-center text-body-sm text-text-dim">
          Already have an account?
          <RouterLink class="text-brand-600 hover:text-brand-700 font-medium focus-visible:ring-2 focus-visible:ring-brand-500 rounded-sm" to="/auth/login">
            Log in
          </RouterLink>
        </div>

        <div class="text-center text-body-xs text-text-dim text-[12px] leading-[16px]">
          After signup you can still test with: test@ticketapp.test / password123
        </div>
      </div>
    </div>

    <footer class="border-t border-surface-border bg-surface py-4 text-center text-body-xs text-text-dim">
      <div class="page-shell">© {{ year }} TicketApp — All rights reserved.</div>
    </footer>
  </main>
</template>

<script setup>
import { ref, reactive, computed } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "../stores/auth.js";
import { isValidationError } from "../utils/errors.js";
import Navbar from "../components/Navbar.vue";

const router = useRouter();
const auth = useAuthStore();

const year = new Date().getFullYear();
const email = ref("");
const password = ref("");
const serverErr = ref(null);

const errors = reactive({ email: "", password: "" });

function validateFields() {
  errors.email = "";
  errors.password = "";
  if (!email.value.trim()) {
    errors.email = "Email is required.";
  } else if (!email.value.includes("@")) {
    errors.email = "Enter a valid email.";
  }
  if (!password.value) {
    errors.password = "Password is required.";
  } else if (password.value.length < 6) {
    errors.password = "Minimum 6 characters.";
  }
}

function fieldServerError(name) {
  return serverErr.value?.details?.fields?.[name] || "";
}

const topLevelMessage = computed(() => {
  if (serverErr.value && isValidationError(serverErr.value)) {
    return serverErr.value.message;
  }
  return null;
});

async function handleSubmit() {
  validateFields();
  if (errors.email || errors.password) return;
  serverErr.value = null;
  const result = await auth.doSignup({ email: email.value.trim(), password: password.value });
  if (!result.ok) {
    serverErr.value = result.error;
    return;
  }
  router.push("/dashboard");
}
</script>
