// src/components/TicketStatusBadge.vue
<template>
  <span class="inline-flex items-center rounded-pill px-2 py-1 text-[12px] leading-[16px] font-medium text-white" :class="badgeClass">
    {{ status }}
  </span>
</template>

<script setup>
import { computed } from "vue";
const props = defineProps({ status: { type: String, required: true } });
const badgeClass = computed(() => {
  if (props.status === "open") return "bg-green-600";
  if (props.status === "in_progress") return "bg-amber-500";
  if (props.status === "closed") return "bg-gray-400";
  return "bg-gray-400";
});
</script>

// src/components/TicketStatusBadge.jsx
import React from "react";

export default function TicketStatusBadge({ status }) {
  let classes = "bg-gray-400 text-white";
  if (status === "open") classes = "bg-green-600 text-white";
  else if (status === "in_progress") classes = "bg-amber-500 text-white";
  else if (status === "closed") classes = "bg-gray-400 text-white";

  return (
    <span
      className={`inline-flex items-center rounded-pill px-2 py-1 text-[12px] leading-[16px] font-medium ${classes}`}
    >
      {status}
    </span>
  );
}
